import Header from "@/components/header";
import NavBar from "@/components/navBar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
